// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqywfiyihqwhbscpdbkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxeXdmaXlpaHF3aGJzY3BkYmtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNDA4MDMsImV4cCI6MjA3NDcxNjgwM30.VXaWqaGl9mWoYx77ewM96cGmS6K4PUwvtQTHhq1v7cw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});